<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?php echo LANG_CODE; ?>"> <!--<![endif]-->
<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Framework template</title>

	<meta name="viewport" content="width=device-width; initial-scale=1.0" />
  	<meta name="description" content="">
  	<meta name="author" content="<?php echo URL; ?>humans.txt">
  	<link type="text/plain" rel="author" href="<?php echo URL; ?>humans.txt" />

	<link rel="stylesheet" href="<?php echo CSS; ?>normalize.css">
	<link rel="stylesheet" href="<?php echo CSS; ?>main.css">

	<!--[if lt IE 9]>

		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
		<script src="<?php echo JS; ?>libs/innershiv.js" type="text/javascript"></script>

	<![endif]-->

	<script src="<?php echo JS; ?>vendor/modernizr-2.6.2.min.js"></script>

</head>

<body>
	<!--[if lt IE 8]><?php echo $t['ancient_browser']; ?><![endif]-->

	<h1>Home phtml</h1>

	<p><?php echo $t['this_is_home_view']; ?></p>

	<p><?php echo $t['select_language']; ?><a href="<?php echo SITE_URL; ?>lang/EN"><?php echo $t['english']; ?></a> <?php echo $t['or']; ?> <a href="<?php echo SITE_URL; ?>lang/ES"><?php echo $t['spanish']; ?></a></p>

	<h2><?php echo $t['info_loaded_through_home_model']; ?></h2>

	<?php foreach ($items as $item) : ?>
		<div><b>ID <?php echo $item['id']; ?>.</b> <?php echo $item['title']; ?></div>
	<?php endforeach; ?>

	<h2><?php echo $t['ajax_test']; ?></h2>

	<p><button type="button" name="btn-ajax" id="btn-ajax"><?php echo $t['click_here']; ?></button></p>

	<div id="ajax-wrap">&nbsp;</div>

	<script>

		var URL_SITE = "<?php echo SITE_URL; ?>";

	</script>


	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="<?php echo JS; ?>vendor/jquery-1.8.2.min.js"><\/script>')</script>

	<script src="<?php echo JS; ?>plugins.js"></script>
	<script src="<?php echo JS; ?>main.js"></script>

	<!--[if lt IE 9]>

		<script type="text/javascript">
				jQuery.ajaxSetup({

					dataFilter: function(data, dataType) {

						if (typeof innerShiv === 'function' && dataType === 'html') {

							return innerShiv(data);

						} else {

							return data;

						}//end else

					}//end dataFilter

				});//end ajaxSetup
		</script>

	<![endif]-->

  	<script>

  		var google_analytics_code = "<?php echo SITE_GOOGLE_ANALYTICS; ?>";

		var _gaq=[['_setAccount', google_analytics_code],['_trackPageview']];
	    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
	    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	    s.parentNode.insertBefore(g,s)}(document,'script'));

  	</script>

</body>
</html>
