<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="<?php echo LANG_CODE; ?>"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="<?php echo LANG_CODE; ?>"> <!--<![endif]-->
<head>

	<meta charset="utf-8">
	<title><?php echo PROJECT_PROJECT_NAME; ?></title>

	<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800">
	<link href="<?php echo CSS; ?>application.css" media="screen" rel="stylesheet" />
	<script src="<?php echo JS; ?>vendor/modernizr-2.6.2.min.js"></script>

	<style>

		.msie{
			padding:50px;
			text-align:center;
		}

			.msie p{
				font-size:25px;
				margin: 50px 0
			}

			.msie a{
				color:#829AB5;
				text-decoration: underline
			}

	</style>

</head>

<body>

	<div class="sidebar-background">
	  <div class="primary-sidebar-background"></div>
	</div>

	<section class="msie">

		<p>Esta aplicación utiliza características del estándar HTML 5 que el navegador<br> <b>Internet Explorer</b> no soporta ni soportará en un futuro cercano.</p>

		<p>Para asegurar una experiencia completa, <br>por favor utiliza el navegador <a href="https://www.google.com/intl/es/chrome/browser/"><b>Google Chrome</b></a>.</p>

	</section>

</body>

</html>